### PR TITLE
Eslint

### PR DESCRIPTION
**Pull request by targos**
To run eslint: `npm run eslint`
Autofix issues: `npm run eslint-fix`

### CODE REVIEW

**Comment by NPellet** [comment]
Is it intended to be merged now ?

**Comment by targos** [comment]
If you are OK with it, yes

**Comment by targos** [comment]
The idea is to add more rules incrementally

**Comment by NPellet** [comment]
Sure

**Comment by NPellet** [comment]
ok, I'll be sure to check them out

**Pull request merged**
