### PR TITLE
fix isData0Array check

### PR DESCRIPTION
**Pull request by targos**
isData0Array does not exist yet at that time and the check will always be true

### CODE REVIEW

**Comment by targos** [comment]
fixes https://github.com/NPellet/visualizer/issues/661

**Comment by NPellet** [comment]
Thank you

**Comment by targos** [comment]
can you make a release please ?

**Comment by NPellet** [comment]
1.12.4-5

Tell me if you encounter issues with shapes. I did some changes for more
consistency in the shape plugin creator

2015-07-30 10:35 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Pull request merged**
