### PR TITLE
Es6

### PR DESCRIPTION
**Pull request by targos**
just opening this to say good luck :)

### CODE REVIEW

**Comment by targos** [comment]
@NPellet WYI this is a new tool that seems useful: https://github.com/FormidableLabs/webpack-dashboard

**Comment by NPellet** [comment]
That's cool. Actually the code runs without problem already, I'm just
working on some new features.
If you have any major suggestion for the migration, let me know.

2016-08-17 9:17 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment]
I'll take a look when I have some time

**Comment by targos** [comment]
I fixed a few issues that I discovered while testing this branch with the visualizer.
The rest mostly LGTM. I think it can be merged to master and we continue the work there ?

**Comment by NPellet** [comment]
No I still need to migrate the plugins

2016-08-23 10:37 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment]
I migrated the broken axes. Do you think you will finish soon with the plugins ?

**Comment by NPellet** [comment]
Ok I'm technically done with the plugins.

I'll do #94 and #96 and then I think we can merge with master

**Comment by NPellet** [comment]
Thanks for your help :)

**Comment by targos** [comment]
np. Can you check that your workflow isn't broken after `npm update` ?

**Comment by targos** [comment]
btw I think that some files are missing in git. I get this error when I build the project:
```
Error: ENOENT: no such file or directory, scandir '/home/mzasso/git/npellet/jsGraph/util/doctemplate/static'
```

**Comment by NPellet** [comment]
Oh maybe it's not tracked properly.
It's the jsdoc template I modified to fit the jsGraph website

2016-10-09 10:25 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Pull request merged**
